### ISSUE TITLE
wrong handling of low accuracy MGRS

### ISSUE THREAD

**Issue by solsticedhiver** [planetfederal/mgrspy#3]
A quick test reveals there is a problem with the handling of low precision MGRS coordinates when converting back to LatLong

Take for example _30UVU76_
```
>>> mgrs.toWgs(u'30UVU7000060000')
(48.39244786357209, -3.4052525061588628)
>>> mgrs.toWgs(u'30UVU70006000')
(47.90058384680606, -4.244344888266018)
>>> mgrs.toWgs(u'30UVU700600')
(47.851066787204594, -4.327375168343752)
>>> mgrs.toWgs(u'30UVU7060')
(47.8461118386288, -4.335669482147029)
>>> mgrs.toWgs(u'30UVU76')
(47.84561631140863, -4.336498826461128)

```
the lat lon converted back are correct when the MGRS ccordinates use a maximum precision (5 digits) but as soon as you remove some of them, you get wrong result which are even outside the 30VU76 grid !

If I am not wrong, you should get
`latlon(30UVU7000060000) = latlon(30VU70006000) = latlon(30UVU700600) = latlon(30UVU7060) = latlon(30UVU76)`

which is not the case given the examples above

using mgrspy from pypi and gdal 2.2.3 in ubuntu 18.04 on python 2.7.15

**Comment by SrNetoChan** [comment]
Please note that the toWGS() function returns the Latitude and Longitude of the lower left corner of the square represented by the MGRS coordinate. While 30UVU7060 represents a 1km sided square, 30UVU76 represents a 10km sided square, which is not the same. Therefore the output coordinate is also not the same.

**Comment by jerheff** [comment]
@SrNetoChan is correct about the coordinates differing, but the output coordinates do not seem to be the lower left corner.

For instance, '17SNA7414' outputs (36.14484431615644, -80.99917743525042) which is far from the lower left corner.   For comparison, this site http://www.legallandconverter.com/cgi-bin/shopmgrs201807.cgi reports a conversion to 36.26810  80.17615, which plots correctly as the lower left corner upon visual inspection in QGIS.

**Comment by solsticedhiver** [comment]
I have never said otherwise.
But even if said MGRS corrdinates repersent a different square, they should return the same lat, lon (the lower left corner for every precision).

So I repeat that from my understanding,

    latlon(30UVU7000060000) = latlon(30VU70006000) = latlon(30UVU700600) = latlon(30UVU7060) = latlon(30UVU76) = (48.39244786357209, -3.4052525061588628)

but this is not what you get with mgrppy

**Comment by dakcarto** [comment]
Tested with latest `mgrspy` v0.3.1 with Python 3.7:
```python
>>> from mgrspy import mgrs
>>> w = mgrs.toWgs(u'30UVU7000060000')
>>> x = mgrs.toWgs(u'30UVU70006000')
>>> y = mgrs.toWgs(u'30UVU700600')
>>> z = mgrs.toWgs(u'30UVU7060')
>>> w == x == y == z
True
>>> x
(48.392447863572094, -3.4052525061588637)
```

Using [GeoConvert](https://geographiclib.sourceforge.io/html/GeoConvert.1.html) from `geographiclib` on the command line (`-n` forces lower-left corner output):
```sh
$> echo 30UVU7000060000 | GeoConvert -g -n -p 9
48.39244786357209 -3.40525250615887
```
which is pretty dang close!

Works as expected with this version. Closing. Please reopen if there are further issues with this.

**Comment by dakcarto** [comment]
@jerheff wrote:
> For instance, '17SNA7414' outputs (36.14484431615644, -80.99917743525042) which is far from the lower left corner. For comparison, this site http://www.legallandconverter.com/cgi-bin/shopmgrs201807.cgi reports a conversion to 36.26810 80.17615, which plots correctly as the lower left corner upon visual inspection in QGIS.

Returns correct lower-left coord for your test case as well now:
```py
>>> from mgrspy import mgrs
>>> mgrs.toWgs('17SNA7414')
(36.26809942516197, -80.17615310641703)
```
and with `GeoConvert`
```
$ echo 17SNA7414 | GeoConvert -g -n -p 9
36.26809942516198 -80.17615310641703
```
