### ISSUE TITLE
Bug in toMgrs routine

### ISSUE THREAD

**Issue by hamiltoncj** [planetfederal/mgrspy#4]
I am getting exceptions in the toMgrs routine since this latest update. For example:

toMgrs(11.43995185735899, 23.601038987469863)
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 142, in toMgrs
  File "<string>", line 408, in _utmToMgrs
  File "<string>", line 487, in _mgrsString
ValueError: -5 is not in list

The version of python is that in QGIS 3.4 and 3.10.

**Comment by dakcarto** [comment]
@hamiltoncj, thanks for the report. Looking into it.

**Comment by dakcarto** [comment]
While I can fix the indexing error, there appears to be a serious GDAL/PROJ v6.x issue, whereby the transformations are very different from PROJ v5. QGIS is having similar issues and there is a fix coming from GDAL and PROJ projects. Will retest when that is available.

**Comment by hamiltoncj** [comment]
QGIS 3.10.1 was just released and mgrs.py is still not functioning correctly and is causing QGIS to hang. This is problematic because it causes Lat Lon Tools to fail with anything MGRS. At least QGIS 3.4.14 is working, but I think they reverted back to the 3.4.12 release.

**Comment by dakcarto** [comment]
@hamiltoncj,

Please try with latest commit on `master`. Note, the coordinate transformation dependency changed from `gdal.osr` to `pyproj` to handle new CRS axis ordering in PROJ 6. I think my fix should not be needed, and maybe can be reverted back to `gdal.osr` once it supports x/y-input -> linked-proj handling via its Python API.

**Comment by dakcarto** [comment]
Fix with `mgrs.py` v0.3.1
